spring.application.name=origin-lock
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration

spring.datasource.url=${ORIGINLOCK_DB_URL:jdbc:postgresql://localhost:5432/originlock}
spring.datasource.username=${ORIGINLOCK_DB_USERNAME:thomphochauke}
spring.datasource.password=${ORIGINLOCK_DB_PASSWORD:}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080
